# Generated by Django 3.1.7 on 2021-03-09 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projects'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='projects',
            table='tb_projects',
        ),
    ]
